// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOtBrY1qgc0Ppn8udMb1iujtwYhUBXuk',
    appId: '1:457013140749:web:cd36110d7ea1d4911ee444',
    messagingSenderId: '457013140749',
    projectId: 'pokinia-lending-manager-c66c7',
    authDomain: 'pokinia-lending-manager-c66c7.firebaseapp.com',
    storageBucket: 'pokinia-lending-manager-c66c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTD4wBbwr56B3HyUc4t43jt128AcHr7o',
    appId: '1:457013140749:android:b14d0fba45c63c2c1ee444',
    messagingSenderId: '457013140749',
    projectId: 'pokinia-lending-manager-c66c7',
    storageBucket: 'pokinia-lending-manager-c66c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgt_0xV6ih5U9kQhRZpNcJ1fzOfDLy-qs',
    appId: '1:457013140749:ios:b5e33f089e63ff9b1ee444',
    messagingSenderId: '457013140749',
    projectId: 'pokinia-lending-manager-c66c7',
    storageBucket: 'pokinia-lending-manager-c66c7.appspot.com',
    iosClientId: '457013140749-oos1jvf4tuou9ca9o7091dfqop83spi9.apps.googleusercontent.com',
    iosBundleId: 'com.pokinia.lendingmanager.pokiniaLendingManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgt_0xV6ih5U9kQhRZpNcJ1fzOfDLy-qs',
    appId: '1:457013140749:ios:427fcb941db7490e1ee444',
    messagingSenderId: '457013140749',
    projectId: 'pokinia-lending-manager-c66c7',
    storageBucket: 'pokinia-lending-manager-c66c7.appspot.com',
    iosClientId: '457013140749-jtebg0vb1c190kab7l7rj3pqsjdq9aji.apps.googleusercontent.com',
    iosBundleId: 'com.pokinia.lendingmanager.pokiniaLendingManager.RunnerTests',
  );
}
